[package]
name = "toml-cli"
version = "0.2.2"
description = "A simple CLI for editing and querying TOML files."
authors = ["Greg Price <gnprice@gmail.com>"]
repository = "https://github.com/gnprice/toml-cli"
readme = "README.md"
license = "MIT"

edition = "2018"

[[bin]]
name = "toml"
path = "src/main.rs"

[[test]]
name = "test"
path = "test/test.rs"

[dependencies]
failure = "0.1"
nom = "5"
serde = "1.0"
serde_json = "1.0"
structopt = "0.3"
toml_edit = "0.15"

[dev-dependencies]
tempfile = "3.3.0"
